export const INITIAL_DEMO_REQUESTS = [
  {
    id: 1,
    initials: "SP",
    name: "Sara Petrović",
    email: "sara@erste-bank.at",
    phone: "+43 1 211 22 33",
    company: "Erste Bank",
    companySize: "5,001+ employees",
    country: "Austria",
    countryCode: "at",
    heardAbout: "Event or Webinar",
    received: "2h ago",
    status: "new",
  },
  {
    id: 2,
    initials: "MW",
    name: "Markus Weber",
    email: "m.weber@db.com",
    phone: "+49 69 910 00",
    company: "Deutsche Bank",
    companySize: "5,001+ employees",
    country: "Germany",
    countryCode: "de",
    heardAbout: "Google",
    received: "5h ago",
    status: "new",
  },
  {
    id: 3,
    initials: "LA",
    name: "Linnéa Andersson",
    email: "linnea@swedbank.se",
    phone: "+46 8 585 900 00",
    company: "Swedbank",
    companySize: "1,001–5,000 employees",
    country: "Sweden",
    countryCode: "se",
    heardAbout: "Work colleague or Partner",
    received: "1d ago",
    status: "contacted",
  },
  {
    id: 4,
    initials: "TN",
    name: "Tomas Novák",
    email: "novak@csas.cz",
    phone: "+420 956 711 711",
    company: "Česká Spořitelna",
    companySize: "1,001–5,000 employees",
    country: "Czech Republic",
    countryCode: "cz",
    heardAbout: "AI Search (like Chat GPT)",
    received: "2d ago",
    status: "booked",
  },
  {
    id: 5,
    initials: "EL",
    name: "Emma Larsson",
    email: "e.larsson@seb.se",
    phone: "+46 771 365 365",
    company: "SEB",
    companySize: "5,001+ employees",
    country: "Sweden",
    countryCode: "se",
    heardAbout: "HR/Retail/Hospitality Network",
    received: "3d ago",
    status: "booked",
  },
  {
    id: 6,
    initials: "PV",
    name: "Pieter de Vries",
    email: "pieter@ing.nl",
    phone: "+31 20 563 9111",
    company: "ING Group",
    companySize: "5,001+ employees",
    country: "Netherlands",
    countryCode: "nl",
    heardAbout: "Social Media",
    received: "5d ago",
    status: "contacted",
  },
  {
    id: 7,
    initials: "AR",
    name: "Ahmed Al-Rashid",
    email: "a.rashid@emiratesnbd.ae",
    phone: "+971 600 540 000",
    company: "Emirates NBD",
    companySize: "5,001+ employees",
    country: "United Arab Emirates",
    countryCode: "ae",
    heardAbout: "Email / Newsletter",
    received: "1w ago",
    status: "new",
  },
  {
    id: 8,
    initials: "YT",
    name: "Yuki Tanaka",
    email: "tanaka@mizuho.jp",
    phone: "+81 3 5224 1111",
    company: "Mizuho Bank",
    companySize: "5,001+ employees",
    country: "Japan",
    countryCode: "jp",
    heardAbout: "Other",
    received: "1w ago",
    status: "contacted",
  },
];

export const STATUSES = ["new", "contacted", "booked"];

export const STATUS_LABEL = {
  new: "New",
  contacted: "Contacted",
  booked: "Booked",
};

export const STATUS_PILL_CLASS = {
  new: "pillNew",
  contacted: "pillContacted",
  booked: "pillBooked",
};

// Status values that get a "View details" page in the modal.
// Idea: a brand-new request might be spam — only confirmed leads (contacted+)
// get a dedicated workspace page.
export const STATUSES_WITH_DETAILS = ["contacted", "booked"];
