// Mock client roster. Swedbank is the rich example used to demo the
// drill-down; other clients have lighter mock data and reuse the same
// shape so any of them renders correctly.

const baseInvoice = (n, date, amount, status = "paid") => ({
  number: n,
  date,
  amount,
  status,
});

const swedbank = {
  id: "swedbank",
  initials: "SB",
  name: "Swedbank",
  countryCode: "se",
  country: "Sweden",
  city: "Stockholm",
  industry: "Banking · retail + corporate",
  size: "12,500 employees",
  domain: "swedbank.se",
  plan: "Enterprise",
  contractValue: "€120,000 / year",
  contractStart: "2026-01-15",
  contractEnd: "2027-01-14",
  seats: { used: 1250, total: 1500 },
  coverage: 96,
  lastActivity: "1d ago",
  primaryContact: {
    initials: "LA",
    name: "Linnéa Andersson",
    role: "Compliance Officer · Admin",
    email: "linnea@swedbank.se",
    phone: "+46 8 585 900 00",
  },
  billingContact: {
    initials: "JH",
    name: "Jonas Hellström",
    role: "Finance Director",
    email: "j.hellstrom@swedbank.se",
    phone: "+46 8 585 900 11",
  },
  programs: [
    { name: "AMLR core",                  roles: "AML Officer, KYC Analyst, Branch Manager", completion: 94 },
    { name: "KYC & Customer Due Diligence", roles: "KYC Analyst, Customer Onboarding",        completion: 88 },
    { name: "Sanctions screening",        roles: "AML Officer, Branch Manager, Risk Officer", completion: 91 },
    { name: "SAR documentation",          roles: "AML Officer, Compliance Lead",              completion: 97 },
    { name: "Beneficial ownership",       roles: "KYC Analyst, Customer Onboarding",          completion: 100 },
  ],
  invoices: [
    baseInvoice("INV-2026-Q1-014", "2026-01-15", "€30,000", "paid"),
    baseInvoice("INV-2025-Q4-118", "2025-10-14", "€30,000", "paid"),
    baseInvoice("INV-2025-Q3-097", "2025-07-15", "€30,000", "paid"),
    baseInvoice("INV-2025-Q2-076", "2025-04-15", "€30,000", "paid"),
  ],
  documents: [
    { name: "Swedbank — Role descriptions Q1 2026.pdf",  size: "1.4 MB",  uploadedBy: "Linnéa Andersson", date: "2026-01-22" },
    { name: "AML Risk Assessment — internal.docx",        size: "880 KB", uploadedBy: "Linnéa Andersson", date: "2026-01-22" },
    { name: "Sanctions policy v4.pdf",                    size: "620 KB", uploadedBy: "Linnéa Andersson", date: "2026-01-20" },
    { name: "Branch network — org chart.xlsx",            size: "240 KB", uploadedBy: "Erik Hellström",   date: "2026-02-03" },
    { name: "Crypto-desk role description.pdf",           size: "1.2 MB", uploadedBy: "Linnéa Andersson", date: "2026-05-10" },
  ],
  notes: [
    { actor: "Kausyar",  text: "Quarterly review scheduled for 12 Jun 2026 — covering AMLR Art. 51 update.", date: "2 days ago" },
    { actor: "Salim",    text: "Approved Crypto Compliance Officer course request, assigned to Kausyar.",   date: "4 hours ago" },
    { actor: "Begimai",  text: "Branch network sync run — 18 new joiners auto-enrolled.",                    date: "1 week ago" },
    { actor: "Kausyar",  text: "Linnéa flagged 7 employees overdue on SAR module — chasing tomorrow.",      date: "2 weeks ago" },
    { actor: "Salim",    text: "Q1 audit report exported and shared with Finansinspektionen.",              date: "3 weeks ago" },
  ],
};

const lighter = (overrides) => ({
  industry: "Banking",
  size: "—",
  domain: "—",
  plan: "Growth",
  contractValue: "—",
  contractStart: "—",
  contractEnd: "—",
  seats: { used: 0, total: 0 },
  primaryContact: { initials: "—", name: "—", role: "—", email: "—", phone: "—" },
  billingContact: { initials: "—", name: "—", role: "—", email: "—", phone: "—" },
  programs: [],
  invoices: [],
  documents: [],
  notes: [],
  ...overrides,
});

export const CLIENTS = [
  swedbank,
  lighter({
    id: "klarna",
    initials: "KL",
    name: "Klarna",
    countryCode: "se",
    country: "Sweden",
    city: "Stockholm",
    industry: "Fintech · BNPL",
    plan: "Enterprise",
    contractValue: "€340,000 / year",
    seats: { used: 4500, total: 5000 },
    coverage: 88,
    lastActivity: "3d ago",
  }),
  lighter({
    id: "seb",
    initials: "SE",
    name: "SEB",
    countryCode: "se",
    country: "Sweden",
    city: "Stockholm",
    industry: "Banking · investment",
    plan: "Enterprise",
    contractValue: "€890,000 / year",
    seats: { used: 12800, total: 14000 },
    coverage: 92,
    lastActivity: "1d ago",
  }),
  lighter({
    id: "avanza",
    initials: "AV",
    name: "Avanza",
    countryCode: "se",
    country: "Sweden",
    city: "Stockholm",
    industry: "Fintech · brokerage",
    plan: "Growth",
    contractValue: "€48,000 / year",
    seats: { used: 540, total: 600 },
    coverage: 100,
    lastActivity: "5h ago",
  }),
  lighter({
    id: "nordea",
    initials: "NO",
    name: "Nordea",
    countryCode: "fi",
    country: "Finland",
    city: "Helsinki",
    industry: "Banking · Nordics",
    plan: "Enterprise",
    contractValue: "€1,240,000 / year",
    seats: { used: 18500, total: 20000 },
    coverage: 89,
    lastActivity: "2d ago",
  }),
  lighter({
    id: "handelsbanken",
    initials: "HB",
    name: "Handelsbanken",
    countryCode: "se",
    country: "Sweden",
    city: "Stockholm",
    industry: "Banking · retail",
    plan: "Enterprise",
    contractValue: "€760,000 / year",
    seats: { used: 11200, total: 12000 },
    coverage: 87,
    lastActivity: "6h ago",
  }),
];

export const getClientById = (id) => CLIENTS.find((c) => c.id === id);
